Drop WebKit
OpenModelica/OMOptim pull request #21
Opened 2023-11-06 19:57 UTC by jschueller

WebKit does seem to be used here (needed for https://github.com/OpenModelica/OpenModelica/pull/9620)

2023-11-06 21:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OpenModelica/OMOptim?pullRequest=21) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OpenModelica/OMOptim?pullRequest=21) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OpenModelica/OMOptim?pullRequest=21) it.</sub>

2023-11-14 08:20 UTC, adeas31 requested changes

2023-11-14 08:20 UTC, adeas31 commented on OMOptim/build/OMOptim.pro
> -}
More better if we made it a single line,

`QT += core gui svg xml printsupport widgets`

2023-11-14 08:24 UTC, adeas31 commented
I meant for all the .pro files.

2023-11-14 08:41 UTC, jschueller commented
done

2023-11-14 08:54 UTC, adeas31 approved these changes

2023-11-14 08:55 UTC, merged